#registry: docker.io
#organization: duckietown
#tag: <distro>-<arch>

# ubuntu:20.04 (focal) and Python3.8
#repository: dt-legacy-py38-environment

# ubuntu:24.04 (noble) and Python3.12
repository: dt-commons
